CREATE TABLE IF NOT EXISTS TENANT_CONFIG (
  ID      INT PRIMARY KEY AUTO_INCREMENT,
  NAME    VARCHAR(100) NOT NULL,
  SEND_WPP TINYINT(1) NOT NULL DEFAULT 0
);

-- Insert default row (update NAME to match your shop name)
INSERT INTO TENANT_CONFIG (NAME, SEND_WPP) VALUES ('MasterCar', 0);
